<a href="https://colab.research.google.com/github/prashast-singh/PyTorch/blob/main/pyTorchFundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [95]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.0+cu121


Introduction to tensors.

*   Creating Tensors





In [96]:
# Scalar (type of a tensor)
# how to create tensor
scalar = torch.tensor(7)
scalar

tensor(7)

In [97]:
#now check the dimenson of tensor
scalar.ndim

0

In [98]:
#get tensor back as python int
scalar.item()

7

In [99]:
# Vector(type of tensor)
vector = torch.tensor([7,7])

In [100]:
#check dimensom of vector tensor
vector.ndim

1

In [101]:
vector.shape

torch.Size([2])

In [102]:
# MATRIX
matrix = torch.tensor([[7,8],[9,19]])
matrix

tensor([[ 7,  8],
        [ 9, 19]])

In [103]:
#dimension od matrix is 2 ie x and y
matrix.ndim

2

In [104]:
# its a 2 x 2 matrix
matrix.shape

torch.Size([2, 2])

In [105]:
matrix[1]

tensor([ 9, 19])

In [106]:
matrix = torch.tensor([[7,8],[9,19],[9,19]])
matrix
matrix.ndim
matrix.shape

torch.Size([3, 2])

In [107]:
# RANDOM tensors

RANDOM TENSORS ARE IMPORTANT BECAUSE?


* The way neural networks learn is that they start with tensors full of random numbers and then they adjust those random numbers to better represent the data.



In [108]:
# create random TENSOR
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.0677, 0.4571, 0.4032, 0.4090],
        [0.9527, 0.4819, 0.2010, 0.6185],
        [0.6179, 0.9318, 0.0394, 0.6090]])

until 1:42:00 watched to be continued

In [109]:
# Creating an tensor similar to image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # heigth width and colour channel (r,g,b)
random_image_size_tensor

tensor([[[0.4585, 0.6269, 0.5635],
         [0.4872, 0.2224, 0.5042],
         [0.9104, 0.6618, 0.7397],
         ...,
         [0.8747, 0.6166, 0.9957],
         [0.9504, 0.1815, 0.1857],
         [0.8702, 0.0306, 0.9095]],

        [[0.8799, 0.1882, 0.5687],
         [0.5269, 0.8480, 0.2410],
         [0.4764, 0.8043, 0.9494],
         ...,
         [0.7348, 0.5921, 0.5962],
         [0.5321, 0.9938, 0.3872],
         [0.1673, 0.1386, 0.2984]],

        [[0.5236, 0.5743, 0.7433],
         [0.4650, 0.3001, 0.2479],
         [0.6170, 0.4197, 0.0370],
         ...,
         [0.8257, 0.5214, 0.3806],
         [0.5025, 0.1172, 0.2222],
         [0.9139, 0.4368, 0.4341]],

        ...,

        [[0.1390, 0.2351, 0.8128],
         [0.8026, 0.8207, 0.3865],
         [0.7617, 0.9225, 0.7559],
         ...,
         [0.9537, 0.2472, 0.1196],
         [0.4516, 0.5654, 0.4984],
         [0.9097, 0.3177, 0.3139]],

        [[0.9330, 0.8392, 0.7731],
         [0.5341, 0.6362, 0.4776],
         [0.

In [110]:
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

** CREATE A TENSOR OF 0 AND 1**

In [111]:
zeros =  torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [112]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [113]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [114]:
ones*random_tensor

tensor([[0.0677, 0.4571, 0.4032, 0.4090],
        [0.9527, 0.4819, 0.2010, 0.6185],
        [0.6179, 0.9318, 0.0394, 0.6090]])

CREATING A RANGE OF TENSOR AND TENSORS LIKE

In [115]:
 one_to_ten = torch.arange(start=1 , end=11, step=1)
 one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [116]:
one_to_ten.shape

torch.Size([10])

In [117]:
#creating a tensor like above without defining shape
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

**TENSOR DATATYPES


 Three major problems are:

 * Tensor not right datatype
 * Tensor not right shape
 * Tensorr not on right device



**

In [118]:
#FLOAT 32 TENSOR
float_32_tensor = torch.tensor([[3.0, 6.0, 9.0]],
                               dtype=None, #what datatype is used for creating tensor
                               device=None, #what device your tensor on cuda, tpu, cpu
                               requires_grad=False) # wheater or not track gradients

In [119]:
float_32_tensor

tensor([[3., 6., 9.]])

In [120]:
float_32_tensor.dtype

torch.float32

In [121]:
float_16_tensor = float_32_tensor.type(torch.float16) #converted float 16 tensor to float 32 tensor

In [122]:
float_16_tensor

tensor([[3., 6., 9.]], dtype=torch.float16)

In [123]:
float_16_tensor.device, float_16_tensor.dtype, float_16_tensor.shape

(device(type='cpu'), torch.float16, torch.Size([1, 3]))

MANIPULATING TENSORS
* ADDITION
* SUBTRACTION
* MULTIPLICATION
* DIVISION
* MATRIX MULTIPLICATION

In [124]:
 tensor = torch.tensor([1,2,3])
 tensor + 100 #addition

tensor([101, 102, 103])

In [125]:
tensor*10 #multiplication

tensor([10, 20, 30])

In [126]:
tensor - 10 #subtraction

tensor([-9, -8, -7])

In [127]:
# tryout tytorch builtin functon
torch.mul(tensor, 10)

tensor([10, 20, 30])

**MATRIX MULTIPLICATION**

In [128]:
# ELEMENT WISE MULTIPLICATION
another_tensor = torch.tensor([[1,2,3]])
print(tensor, '*', tensor)
print(tensor*tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
tensor([1, 4, 9])


In [129]:
#matrix multolication
torch.matmul(tensor, tensor), another_tensor.shape, tensor.shape

(tensor(14), torch.Size([1, 3]), torch.Size([3]))

In [130]:
#torch.matmul(tensor, another_tensor)

**IN MATMUL THE INNER DIMENSIONS MUST MATCH**
EG. (2,3) WILL MULTIPLY (3,2) SHAPE

* the resulting matrix has outer dimension rg. shape: (2,3)@(3,2) -> (2,2)

In [131]:
tensor_A = torch.tensor([[1,2],[3,4], [5,6]])
tensor_B = torch.tensor([[7,10],[8,11], [9,12]])
tensor_A.shape , tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [132]:
# torch.matmul(tensor_A, tensor_B)
# solution for this error is to make transpose of one tensor coz
#transpose does not chnage determinant of matrix

In [134]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [135]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])