<a href="https://colab.research.google.com/github/prashast-singh/PyTorch/blob/main/pyTorchFundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.0+cu121


Introduction to tensors.

*   Creating Tensors





In [3]:
# Scalar (type of a tensor)
# how to create tensor
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
#now check the dimenson of tensor
scalar.ndim

0

In [5]:
#get tensor back as python int
scalar.item()

7

In [6]:
# Vector(type of tensor)
vector = torch.tensor([7,7])

In [7]:
#check dimensom of vector tensor
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# MATRIX
matrix = torch.tensor([[7,8],[9,19]])
matrix

tensor([[ 7,  8],
        [ 9, 19]])

In [10]:
#dimension od matrix is 2 ie x and y
matrix.ndim

2

In [11]:
# its a 2 x 2 matrix
matrix.shape

torch.Size([2, 2])

In [12]:
matrix[1]

tensor([ 9, 19])

In [13]:
matrix = torch.tensor([[7,8],[9,19],[9,19]])
matrix
matrix.ndim
matrix.shape

torch.Size([3, 2])

In [14]:
# RANDOM tensors

RANDOM TENSORS ARE IMPORTANT BECAUSE?


* The way neural networks learn is that they start with tensors full of random numbers and then they adjust those random numbers to better represent the data.



In [15]:
# create random TENSOR
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.1491, 0.8547, 0.6659, 0.8675],
        [0.8424, 0.8107, 0.1954, 0.1779],
        [0.2371, 0.4206, 0.5907, 0.1407]])

until 1:42:00 watched to be continued

In [16]:
# Creating an tensor similar to image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # heigth width and colour channel (r,g,b)
random_image_size_tensor

tensor([[[0.3989, 0.9717, 0.5106],
         [0.3770, 0.2267, 0.3077],
         [0.6677, 0.7641, 0.1583],
         ...,
         [0.1285, 0.3811, 0.5100],
         [0.5225, 0.8314, 0.3625],
         [0.7230, 0.2118, 0.7107]],

        [[0.8042, 0.7646, 0.1380],
         [0.2959, 0.0051, 0.2014],
         [0.0712, 0.8083, 0.5153],
         ...,
         [0.0901, 0.3709, 0.9617],
         [0.1201, 0.2961, 0.1279],
         [0.4679, 0.4480, 0.0845]],

        [[0.9556, 0.7711, 0.1745],
         [0.8622, 0.3246, 0.4069],
         [0.1796, 0.9136, 0.1904],
         ...,
         [0.4648, 0.5861, 0.4773],
         [0.4644, 0.3428, 0.9140],
         [0.2708, 0.6531, 0.9760]],

        ...,

        [[0.4968, 0.9877, 0.0321],
         [0.2557, 0.2736, 0.3811],
         [0.3060, 0.8309, 0.0710],
         ...,
         [0.3022, 0.8324, 0.7987],
         [0.9666, 0.1953, 0.2913],
         [0.4228, 0.2696, 0.1563]],

        [[0.7556, 0.8294, 0.3247],
         [0.0756, 0.4070, 0.3795],
         [0.

In [17]:
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

** CREATE A TENSOR OF 0 AND 1**

In [18]:
zeros =  torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
ones*random_tensor

tensor([[0.1491, 0.8547, 0.6659, 0.8675],
        [0.8424, 0.8107, 0.1954, 0.1779],
        [0.2371, 0.4206, 0.5907, 0.1407]])

CREATING A RANGE OF TENSOR AND TENSORS LIKE

In [22]:
 one_to_ten = torch.arange(start=1 , end=11, step=1)
 one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
one_to_ten.shape

torch.Size([10])

In [24]:
#creating a tensor like above without defining shape
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

**TENSOR DATATYPES**

In [25]:
#FLOAT 32 TENSOR
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)